"""Central configuration for Phase 5 modelling.

Phase 5 builds on the validated Phase 4 outputs and implements the project's
first machine-learning component: relative LST heat-severity classification
using Random Forest and XGBoost with spatially aware validation.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Resolve project root robustly whether this file is imported directly or
# via a package import.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
src_dir = PROJECT_ROOT / "src"
if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

from features.config import (  # noqa: E402
    COMBINED_DATASET_CSV,
    PHASE4_DIR,
    REFERENCE_RASTER_PATH,
    RANDOM_SEED as FEATURES_RANDOM_SEED,
)

# ---------------------------------------------------------------------------
# Phase 5 directories
# ---------------------------------------------------------------------------
PHASE5_DIR = PROJECT_ROOT / "data" / "processed" / "phase5"
PHASE5_MODELS_DIR = PHASE5_DIR / "models"
PHASE5_PREDICTIONS_DIR = PHASE5_DIR / "predictions"
PHASE5_PROBABILITIES_DIR = PHASE5_DIR / "probabilities"
PHASE5_MAPS_DIR = PHASE5_DIR / "maps"
PHASE5_TABLES_DIR = PHASE5_DIR / "tables"

for _d in (
    PHASE5_MODELS_DIR,
    PHASE5_PREDICTIONS_DIR,
    PHASE5_PROBABILITIES_DIR,
    PHASE5_MAPS_DIR,
    PHASE5_TABLES_DIR,
):
    _d.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Input dataset
# ---------------------------------------------------------------------------
INPUT_DATASET_CSV = COMBINED_DATASET_CSV
REFERENCE_RASTER = REFERENCE_RASTER_PATH

# ---------------------------------------------------------------------------
# Column definitions
# ---------------------------------------------------------------------------
TARGET_VAR = "lst_C"
GROUP_VAR = "spatial_block_id"
YEAR_VAR = "year"

IDENTIFIER_VARS = ["lon", "lat", "row", "col"]

CATEGORICAL_VARS = ["landuse_class"]

# ---------------------------------------------------------------------------
# Spatial neighbourhood features
# ---------------------------------------------------------------------------
# Block-aware focal means of base predictors at 3×3, 5×5, and 11×11 scales.
# These are computed once from the Phase 4 rasters and merged into the dataset.
USE_SPATIAL_FEATURES = True
SPATIAL_WINDOW_SIZES = [3, 5, 11]
SPATIAL_FEATURE_BASES = [
    "ndvi",
    "ndbi",
    "vegetation_cover",
    "dist_road_m",
    "dist_vegetation_m",
    "dist_building_m",
]
SPATIAL_FEATURE_COLS = [
    f"{feature}_mean{window}"
    for feature in SPATIAL_FEATURE_BASES
    for window in SPATIAL_WINDOW_SIZES
]

# ---------------------------------------------------------------------------
# Urban morphology features
# ---------------------------------------------------------------------------
# Block-aware circular-neighbourhood features derived from existing Phase 3/4
# rasters only.  A pixel's neighbourhood is restricted to its own spatial block,
# so no cross-block information leaks into the feature.  This causes block-edge
# kernel truncation; the number of clipped pixels is reported by the feature
# builder and should be noted when interpreting the 500 m features in particular.
USE_MORPHOLOGY_FEATURES = True
MORPHOLOGY_RADII_M = [50, 100, 250, 500]
MORPHOLOGY_RESOLUTION_M = 30.0
MORPHOLOGY_LANDUSE_CLASSES = [1, 2, 3, 4, 5, 6, 7, 8]


def get_morphology_feature_columns() -> list[str]:
    """Return the column names generated by the morphology feature builder."""
    cols = []
    for radius in MORPHOLOGY_RADII_M:
        cols.append(f"building_pixel_fraction_{radius}m")
        cols.append(f"road_pixel_fraction_{radius}m")
        cols.append(f"vegetation_pixel_fraction_{radius}m")
        cols.append(f"vegetation_cover_mean_{radius}m")
        for lu in MORPHOLOGY_LANDUSE_CLASSES:
            cols.append(f"landuse_frac_{lu}_{radius}m")
        cols.append(f"landuse_dominant_{radius}m")
        cols.append(f"landuse_entropy_{radius}m")
        cols.append(f"ndvi_contrast_{radius}m")
        cols.append(f"ndbi_contrast_{radius}m")
    return cols


MORPHOLOGY_FEATURE_COLS = get_morphology_feature_columns()

# Base predictors (no spatial context).
BASE_PREDICTOR_VARS = [
    "ndvi",
    "ndbi",
    "vegetation_cover",
    "landuse_class",
    "dist_road_m",
    "dist_vegetation_m",
    "dist_building_m",
    YEAR_VAR,
]

SPATIAL_ONLY_PREDICTOR_VARS = BASE_PREDICTOR_VARS + SPATIAL_FEATURE_COLS
MORPHOLOGY_ONLY_PREDICTOR_VARS = BASE_PREDICTOR_VARS + MORPHOLOGY_FEATURE_COLS

# Full predictor set including spatial and morphology features.
PREDICTOR_VARS = BASE_PREDICTOR_VARS + SPATIAL_FEATURE_COLS + MORPHOLOGY_FEATURE_COLS

# All columns that must be present in the raw Phase 4 input dataset.
# Spatial features are merged afterwards and are not required in the CSV.
REQUIRED_INPUT_COLS = (
    IDENTIFIER_VARS
    + [GROUP_VAR, YEAR_VAR, TARGET_VAR]
    + BASE_PREDICTOR_VARS
)

# ---------------------------------------------------------------------------
# Target definition
# ---------------------------------------------------------------------------
# Four relative heat-severity classes derived from per-year LST quartiles.
CLASS_LABELS = ["Low", "Moderate", "High", "Severe"]
CLASS_VALUES = [0, 1, 2, 3]
CLASS_MAPPING = dict(zip(CLASS_LABELS, CLASS_VALUES))
INV_CLASS_MAPPING = {v: k for k, v in CLASS_MAPPING.items()}

# Quartile thresholds used to define classes within each year.
TARGET_QUANTILES = [0.0, 0.25, 0.50, 0.75, 1.0]

# ---------------------------------------------------------------------------
# Model configuration
# ---------------------------------------------------------------------------
RANDOM_SEED = FEATURES_RANDOM_SEED
N_SPATIAL_FOLDS = 5

RANDOM_FOREST_PARAMS = {
    "n_estimators": 200,
    "max_depth": None,
    "min_samples_split": 5,
    "min_samples_leaf": 2,
    "max_features": "sqrt",
    "class_weight": "balanced",
    "random_state": RANDOM_SEED,
    "n_jobs": -1,
}

XGBOOST_PARAMS = {
    "n_estimators": 200,
    "learning_rate": 0.05,
    "max_depth": 6,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "objective": "multi:softprob",
    "eval_metric": "mlogloss",
    "random_state": RANDOM_SEED,
    "n_jobs": -1,
}

# ---------------------------------------------------------------------------
# Output files
# ---------------------------------------------------------------------------
MODEL_METADATA_JSON = PHASE5_DIR / "phase5_model_metadata.json"
PIPELINE_RECORD_JSON = PHASE5_DIR / "phase5_pipeline_record.json"
VALIDATION_REPORT_JSON = PHASE5_DIR / "phase5_validation_report.json"

PREDICTIONS_CSV = PHASE5_TABLES_DIR / "predictions.csv"
MODEL_COMPARISON_CSV = PHASE5_TABLES_DIR / "model_comparison.csv"
CLASSIFICATION_METRICS_CSV = PHASE5_TABLES_DIR / "classification_metrics.csv"
FEATURE_IMPORTANCE_CSV = PHASE5_TABLES_DIR / "feature_importance.csv"
ABLATION_RESULTS_CSV = PHASE5_TABLES_DIR / "ablation_results.csv"

OOF_PREDICTIONS_CSV = PHASE5_TABLES_DIR / "oof_predictions.csv"
CONFUSION_MATRICES_CSV = PHASE5_TABLES_DIR / "confusion_matrices.csv"
BOUNDARY_CASE_ANALYSIS_CSV = PHASE5_TABLES_DIR / "boundary_case_analysis.csv"
PERMUTATION_IMPORTANCE_CSV = PHASE5_TABLES_DIR / "permutation_importance.csv"
MORPHOLOGY_FEATURES_CSV = PHASE5_TABLES_DIR / "morphology_features.csv"

UHI_RASTER_2022 = PHASE5_PREDICTIONS_DIR / "uhi_2022.tif"
UHI_RASTER_2026 = PHASE5_PREDICTIONS_DIR / "uhi_2026.tif"

UHI_MAP_2022 = PHASE5_MAPS_DIR / "uhi_2022.png"
UHI_MAP_2026 = PHASE5_MAPS_DIR / "uhi_2026.png"

# ---------------------------------------------------------------------------
# Probability outputs
# ---------------------------------------------------------------------------
PROBABILITY_RASTERS = {
    year: {
        label: PHASE5_PROBABILITIES_DIR / f"probability_{label.lower()}_{year}.tif"
        for label in CLASS_LABELS
    }
    for year in (2022, 2026)
}

CONFIDENCE_RASTER_2022 = PHASE5_PROBABILITIES_DIR / "confidence_2022.tif"
CONFIDENCE_RASTER_2026 = PHASE5_PROBABILITIES_DIR / "confidence_2026.tif"

__all__ = [
    "PROJECT_ROOT",
    "PHASE5_DIR",
    "PHASE5_MODELS_DIR",
    "PHASE5_PREDICTIONS_DIR",
    "PHASE5_PROBABILITIES_DIR",
    "PHASE5_MAPS_DIR",
    "PHASE5_TABLES_DIR",
    "INPUT_DATASET_CSV",
    "REFERENCE_RASTER",
    "TARGET_VAR",
    "GROUP_VAR",
    "YEAR_VAR",
    "IDENTIFIER_VARS",
    "PREDICTOR_VARS",
    "BASE_PREDICTOR_VARS",
    "SPATIAL_FEATURE_COLS",
    "SPATIAL_ONLY_PREDICTOR_VARS",
    "MORPHOLOGY_FEATURE_COLS",
    "MORPHOLOGY_ONLY_PREDICTOR_VARS",
    "USE_MORPHOLOGY_FEATURES",
    "MORPHOLOGY_RADII_M",
    "MORPHOLOGY_LANDUSE_CLASSES",
    "CATEGORICAL_VARS",
    "REQUIRED_INPUT_COLS",
    "CLASS_LABELS",
    "CLASS_VALUES",
    "CLASS_MAPPING",
    "INV_CLASS_MAPPING",
    "TARGET_QUANTILES",
    "RANDOM_SEED",
    "N_SPATIAL_FOLDS",
    "RANDOM_FOREST_PARAMS",
    "XGBOOST_PARAMS",
    "MODEL_METADATA_JSON",
    "PIPELINE_RECORD_JSON",
    "VALIDATION_REPORT_JSON",
    "PREDICTIONS_CSV",
    "MODEL_COMPARISON_CSV",
    "CLASSIFICATION_METRICS_CSV",
    "FEATURE_IMPORTANCE_CSV",
    "ABLATION_RESULTS_CSV",
    "OOF_PREDICTIONS_CSV",
    "CONFUSION_MATRICES_CSV",
    "BOUNDARY_CASE_ANALYSIS_CSV",
    "PERMUTATION_IMPORTANCE_CSV",
    "MORPHOLOGY_FEATURES_CSV",
    "UHI_RASTER_2022",
    "UHI_RASTER_2026",
    "UHI_MAP_2022",
    "UHI_MAP_2026",
    "PROBABILITY_RASTERS",
    "CONFIDENCE_RASTER_2022",
    "CONFIDENCE_RASTER_2026",
]
